// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using ONE.Abp.DataPermission.Rules;
using ONE.Abp.Pagination.Contracts.Dtos;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace ONE.Abp.DataPermission.Rules;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IDataTargetAppService), typeof(DataTargetClientProxy))]
public partial class DataTargetClientProxy : ClientProxyBase<IDataTargetAppService>, IDataTargetAppService
{
    public virtual async Task<DataTargetDto> GetAsync(string name)
    {
        return await RequestAsync<DataTargetDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), name }
        });
    }

    public virtual async Task<ListResultDto<DataTargetDto>> GetListAsync()
    {
        return await RequestAsync<ListResultDto<DataTargetDto>>(nameof(GetListAsync));
    }

    public virtual async Task<PagedResult<DataTargetDto>> QueryAsync(DataTargetQueryInput input)
    {
        return await RequestAsync<PagedResult<DataTargetDto>>(nameof(QueryAsync), new ClientProxyRequestTypeValue
        {
            { typeof(DataTargetQueryInput), input }
        });
    }
}
